package xyz.haff.apisecurity.database

import org.dalesbred.Database

fun Database.withAutoGeneratedId(sequenceName: String, func: Database.(id: Long) -> Unit): Long = withTransaction {
    val id = findUniqueLong("SELECT NEXT VALUE FOR $sequenceName")
    func(id)
    return@withTransaction id
}